apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - video-platform.yaml
  - video-dashboard.yaml
  - video-edge.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: video-system
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
